using System;
using System.ServiceModel.Syndication;

namespace Opds4Net.Server
{
    /// <summary>
    /// The event arguments for the ItemGenerated event in IOpdsItemConverter.
    /// </summary>
    public class ItemGeneratedEventArgs : EventArgs
    {
        /// <summary>
        /// Default constructor of ItemGeneratedEventArgs
        /// </summary>
        /// <param name="item">Syndication generated by the IOpdsItemConverter.</param>
        /// <param name="data">Data used to generate the SyndicationItem.</param>
        public ItemGeneratedEventArgs(SyndicationItem item, object data)
        {
            Item = item;
            Data = data;
        }

        /// <summary>
        /// The data used to generate the SyndicationItem.
        /// </summary>
        public object Data { get; private set; }

        /// <summary>
        /// The SyndicationItem generated from the Data.
        /// </summary>
        public SyndicationItem Item { get; private set; }
    }
}
